name: Flutter Build [macOS Silicon]
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build_macos_silicon:
    runs-on: macos-13-xlarge  # macOS Silicon
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS app
        run: |
          flutter build macos

